# Site settings
title: jalyna.github.io
email: jalyna.schroeder@gmail.com
description: ""
baseurl: ""
url: "http://jalyna.io"
twitter_username: jalynas
github_username:  jalyna

# Build settings
markdown: kramdown
permalink: pretty
